import type { ArticleSection } from '../types'

export const redliningArticle = {
  title: "Redlining and Heart Disease",
  subtitle: "How a 1930s Housing Policy Still Shapes Cardiovascular Risk",
  author: "Voices of Equity Education Team",
  date: "April 2026",
  sections: [
    {
      type: 'heading',
      text: 'Introduction'
    },
    {
      type: 'paragraph',
      text: 'Discriminatory practices created decades ago still affect the health of Americans to this day. Redlining, a housing policy created by federal officials in the 1930s, continues to increase rates of heart attack, heart failure, and stroke. These health impacts are not coincidence, but a consequence of structural racism encoded in geography. This history matters to physicians, policy makers, and members of the community who seek to understand why heart disease disproportionately burdens Black, Brown, and low-income Americans.'
    },
    {
      type: 'heading',
      text: 'What Was Redlining?'
    },
    {
      type: 'paragraph',
      text: 'In 1933, the federal government created the Home Owners\u2019 Loan Corporation (HOLC) to aid homeowners in avoiding foreclosure during the Great Depression. In the late 1930s, HOLC launched the City Survey Program, which produced color-coded \u201cResidential Security Maps\u201d for nearly 250 cities. Neighborhoods were color-coded as A (green, \u201cBest\u201d) through D (red, \u201cHazardous\u201d), giving rise to the term redlining.'
    },
    {
      type: 'paragraph',
      text: 'The City Survey Program was discriminatory by design. Appraisers from HOLC directly accounted for race in their neighborhood assessments and treated the presence of Black and minority populations as a financial risk. Populations with majority Black neighborhoods often assigned the red category, regardless of actual housing quality.'
    },
    {
      type: 'paragraph',
      text: 'These marginalized communities, which were cut off from conventional mortgages, insurance, and investment, saw decay in infrastructure and cycles of poverty. In 1968, the Fair Housing Act formally prohibited explicit redlining, but could not eradicate the existing housing inequality. A 2018 analysis by the National Community Reinvestment Coalition found that 74% of formerly hazardous neighborhoods remain low-to-moderate income today, and 64% remain majority nonwhite (National Community Reinvestment Coalition, 2018).'
    },
    {
      type: 'heading',
      text: 'Heat Exposure as a Cardiovascular Stressor'
    },
    {
      type: 'paragraph',
      text: 'Formerly redlined neighborhoods are notably hotter than the rest of their cities. Cycles of disinvestment have left these areas with less trees and green infrastructure, contributing to an urban heat island effect.'
    },
    {
      type: 'paragraph',
      text: 'A 2020 study that examines summer land surface temperatures and HOLC grades in 108 U.S. urban areas found that formerly redlined (grade D) neighborhoods experienced significantly higher temperatures than the highest graded regions, a pattern that occurred in 94% of cities studied. The authors of the study concluded that \u201ccurrent maps of intra-urban heat echo the legacy of past planning policies\u201d (Hoffman et al., 2020).'
    },
    {
      type: 'paragraph',
      text: 'The cardiovascular consequences of heat exposure are well documented. Heat triggers sympathetic nervous system responses that increase heart rate and cardiac stress. These triggers also promote dehydration and electrolyte imbalances that predispose to abnormal heart rhythms. A systematic review of 282 studies found that for each 1\u00b0C rise in ambient temperature, there was an associated 2.1% increase in cardiovascular mortality, with the highest risks for stroke and coronary heart disease (Zhao et al., 2022).'
    },
    {
      type: 'paragraph',
      text: 'Ultimately, formerly redlined communities carry higher rates of hypertension, diabetes, heart failure, and chronic kidney disease.'
    },
    {
      type: 'heading',
      text: 'Air Pollution and Vascular Risk'
    },
    {
      type: 'paragraph',
      text: 'In addition to excess heat, formerly redlined neighborhoods experience a disproportionate amount of air pollution. Discriminatory zoning practices placed industrial facilities, waste plants, and roadways within or near communities of color, causing toxic exposure.'
    },
    {
      type: 'paragraph',
      text: 'Fine particulate matter (PM2.5) are particles 2.5 micrometers or smaller that are generated by vehicle exhaust, power plants, and industrial combustion. PM2.5 penetrates the lungs and crosses directly into the bloodstream, through which short term exposure may raise acute coronary syndrome and arrhythmia risk. Long term exposure to PM2.5 is linked to subclinical atherosclerosis, heart failure, cerebrovascular disease, and cardiovascular mortality (Al-Kindi et al., 2023).'
    },
    {
      type: 'paragraph',
      text: 'A study of nearly 60 million Medicare beneficiaries found that chronic PM2.5 exposure increased first hospitalization risk across all major cardiovascular subtypes. Even at low concentration, risk remained elevated (Wei et al., 2024). Moreover, even PM2.5 at approximately 15 \u00b5g/m\u00b3, a level the WHO designates as an interim target, was associated with measurable increases in vascular calcification (Shi et al., 2024). People living in historically redlined neighborhoods who live in close proximity to pollution sources are exposed to these dangerous particles that impact their health on a daily basis.'
    },
    {
      type: 'heading',
      text: 'Direct Cardiovascular Outcome Evidence'
    },
    {
      type: 'paragraph',
      text: 'Historical redlining is linked to worse cardiovascular outcomes today. A 2023 cohort study in JAMA Network Open, examining 79,997 U.S. veterans with established atherosclerotic cardiovascular disease, assigned each veteran\u2019s residence to an HOLC grade and tracked major adverse cardiovascular events (MACE: myocardial infarction, stroke, major adverse extremity events, and all-cause mortality) over a median four-year follow-up.'
    },
    {
      type: 'paragraph',
      text: 'It was found that veterans in formerly redlined (grade D) neighborhoods had a 13.9% higher MACE risk (HR 1.139; 95% CI, 1.083\u20131.198; P < .001) and a 12.9% higher all-cause mortality risk (HR 1.129; 95% CI, 1.072\u20131.190; P < .001) compared to those in the highest-rated areas. The authors concluded that \u201cone\u2019s surrounding environment is a powerful estimator of health\u201d (Deo et al., 2023).'
    },
    {
      type: 'paragraph',
      text: 'Research using the Multi-Ethnic Study of Atherosclerosis (MESA) cohort also found that Black adults in formerly redlined areas had measurably lower composite cardiovascular health scores than those in highest-rated neighborhoods (Mujahid et al., 2021). The authors state that \u201credlining is another manifestation of structural racism whose legacy is driving health disparities today.\u201d'
    },
    {
      type: 'heading',
      text: 'Implications'
    },
    {
      type: 'paragraph',
      text: 'Even though redlining was instituted in the 1930s, it actively worsens health outcomes and shortens lives of residents in communities who were affected by it. Redlining is a structural issue that demands a structural response.'
    },
    {
      type: 'paragraph',
      text: 'For clinicians, this means that cardiovascular risk assessment must incorporate neighborhood history alongside individual clinical variables. A patient\u2019s residential location carries diagnostic information that standard risk calculators miss. Heart disease disparities in low-income communities are not only the products of genetics or lifestyle, but more so the policy decisions that have instituted cycles of poverty and environmental harm.'
    },
    {
      type: 'paragraph',
      text: 'For patients and community members, it is worth mentioning to your healthcare provider if your general area of residence is located near polluted areas, heat islands, or other environmental hazards. These environmental factors can influence your cardiovascular health in ways that may not be captured by routine clinical assessments.'
    },
    {
      type: 'paragraph',
      text: 'In many cities, the neighborhoods marked red nine decades ago remain the poorest and most medically underserved. Health equity requires acknowledging these geographical inequalities that contribute to vastly different health outcomes.'
    },
    {
      type: 'heading',
      text: 'References'
    },
    {
      type: 'citation',
      items: [
        'Al-Kindi, S., Rajagopalan, S., & Motairek, I. (2023). Environmental pollution and cardiovascular disease: Part 1 of 2: Air pollution. JACC: Advances, 2(10), 100805.',
        'Deo, S. V., Motairek, I., Nasir, K., et al. (2023). Association between historical neighborhood redlining and cardiovascular outcomes among U.S. veterans with atherosclerotic cardiovascular diseases. JAMA Network Open, 6(7), e2322727.',
        'Hoffman, J. S., Shandas, V., & Pendleton, N. (2020). The effects of historical housing policies on resident exposure to intra-urban heat: A study of 108 U.S. urban areas. Climate, 8(1), 12.',
        'Mujahid, M. S., Gao, X., Tabb, L. P., et al. (2021). Historical redlining and cardiovascular health: The Multi-Ethnic Study of Atherosclerosis. PNAS, 118(51), e2110986118.',
        'National Community Reinvestment Coalition. (2018). HOLC \u201credlining\u201d maps: The persistent structure of segregation and economic inequality.',
        'Shi, X., Liu, X., Wang, J., & Chen, Y. (2024). New insight into air pollution-related cardiovascular disease: An adverse outcome pathway framework of PM2.5-associated vascular calcification. Cardiovascular Research, 120(7), 699\u2013714.',
        'Wei, Y., Feng, Y., Danesh Yazdi, M., et al. (2024). Exposure-response associations between chronic exposure to fine particulate matter and risks of hospital admission for major cardiovascular diseases. BMJ, 384, e076939.',
        'Zhao, Q., Guo, Y., Ye, T., et al. (2022). Global, regional, and national burden of mortality associated with non-optimal ambient temperatures from 2000 to 2019. The Lancet Planetary Health, 6(5), e415\u2013e425.'
      ]
    }
  ] satisfies ArticleSection[]
}
